language: python
python:
  # as we support centos, which only has 2.6, we use this.
  # in theory, there is no issue with 2.7 at all
  - "2.6"

install:
  - git submodule update --init --recursive

script:
  - echo "if the checkout works, I am happy already"